sudo: required

services:
  - docker

before_install:
  - sed -i.bak -e "s|<username>|$USERNAME|g" datastax.sources.list
  - sed -i.bak -e "s|<password>|$PASSWORD|g" datastax.sources.list

install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  # http://suda.pl/build-and-push-docker-images-using-travis/
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
